{"uuid": "a92a5aa9-38ec-43f6-924b-871740542855", "children": ["2be95bab-87c3-4f66-9c40-76b7d061bf6d", "c55dac83-6a21-4a97-b40b-9f449e9882f7"], "befores": [{"name": "init_request", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v3/work_packages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FD0221610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\tests\\test_7.py\", line 18, in init_request\n    response = ProjectApi().post_new_work_package(self.new_work_package_name)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\project_api.py\", line 88, in post_new_work_package\n    response = super().post(path=\"/api/v3/work_packages\", payload=payload)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\rest_client.py\", line 26, in post\n    response = requests.request(\"POST\", url=self.__base_url + path, headers=self.__headers, data=payload)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1625586303274, "stop": 1625586307282}], "start": 1625586303274, "stop": 1625586311612}