{"uuid": "1451f3a0-b6eb-4c3d-888e-1df3a5123a7d", "children": ["0b98aa68-b90a-4aee-a6c2-85d750779956", "1d972085-7934-495b-aa0d-944de832ada6"], "befores": [{"name": "init_patch_request", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v3/work_packages/34 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FCFD02AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\tests\\test_6.py\", line 14, in init_patch_request\n    response = ProjectApi().get_work_package_by_id(self.work_package_id)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\project_api.py\", line 45, in get_work_package_by_id\n    response = super().get(path=f\"/api/v3/work_packages/{work_package_id}\")\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\rest_client.py\", line 16, in get\n    response = requests.request(\"GET\", url=self.__base_url + path, headers=self.__headers)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1625586298934, "stop": 1625586302940}], "start": 1625586298934, "stop": 1625586311612}