{"uuid": "a2130421-159a-475b-941f-85cddc08a61c", "children": ["1d71a783-c4a7-4aa4-a4ee-053b73e3130f", "c4384a2f-c95e-4a33-870d-84caea996dbe", "a023e34b-6f3d-4826-8190-cca14d62a291"], "befores": [{"name": "init_get_request", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v3/projects/3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FCF9F5EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\tests\\test_1.py\", line 13, in init_get_request\n    response = ProjectApi().get_project_by_id(self.project_id)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\project_api.py\", line 13, in get_project_by_id\n    response = super().get(path=f\"/api/v3/projects/{project_id}\")\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\rest_client.py\", line 16, in get\n    response = requests.request(\"GET\", url=self.__base_url + path, headers=self.__headers)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1625586277537, "stop": 1625586281554}], "start": 1625586277537, "stop": 1625586311615}