{"uuid": "89df3a93-23a9-494e-9b32-3fc6c3106cfa", "children": ["fea652a2-cd7f-49a6-bed2-59c8aa7b056a"], "befores": [{"name": "init_create_work_space", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v3/work_packages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FD026CC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\tests\\test_8.py\", line 21, in init_create_work_space\n    response = ProjectApi().post_new_work_package(self.new_work_package_name)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\project_api.py\", line 88, in post_new_work_package\n    response = super().post(path=\"/api/v3/work_packages\", payload=payload)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\rest_client.py\", line 26, in post\n    response = requests.request(\"POST\", url=self.__base_url + path, headers=self.__headers, data=payload)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1625586307503, "stop": 1625586311509}], "start": 1625586307503, "stop": 1625586311610}