{"name": "test_second", "status": "failed", "statusDetails": {"message": "AssertionError: Houston we've got a problem\nassert 4 == 5", "trace": "self = <test_1.TestOne object at 0x000001EAF38BB160>\ninit_web_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"511e26783f674abfdec3371697e74c47\")>\n\n    @pytest.mark.sanity\n    def test_second(self, init_web_driver):\n        init_web_driver.get(\"https://www.gmail.com\")\n>       assert 2 + 2 == 5, \"Houston we've got a problem\"\nE       AssertionError: Houston we've got a problem\nE       assert 4 == 5\n\ntest_1.py:23: AssertionError"}, "start": 1623695181741, "stop": 1623695184190, "uuid": "fc61cab8-2aa5-47d7-a8ba-ec5daf46aa04", "historyId": "18eab4814b7571795a9a00922c03716f", "testCaseId": "a67ff91e5296a75f95cbfd9f194a279c", "fullName": "test_1.TestOne#test_second", "labels": [{"name": "tag", "value": "system"}, {"name": "tag", "value": "sanity"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite", "value": "TestOne"}, {"name": "host", "value": "LAPTOP-KHP8ML6J"}, {"name": "thread", "value": "17976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}